version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # 5433 en el Local porque ya se tiene PosgreSQL en la PC y 5432 en el puerto del contenedor 
    volumes:
      - ./postgres:/var/lib/postgresql/data
    